package co.edu.udistrital.view.control;

import co.edu.udistrital.exception.PLCCommunicationException;
import co.edu.udistrital.plc.communication.PLCCommunication;
import co.edu.udistrital.service.ApplicationServices;
import co.edu.udistrital.view.InitApplication;
import co.edu.udistrital.view.configuration.EmailConfigurationDialog;
import com.spinn3r.log5j.Logger;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.*;

import java.math.BigDecimal;

/**
 * Created by frealgagu on 5/10/14.
 */
public class ChangeRegisterValueDialog extends CustomComponent {

    protected static final Logger logger = Logger.getLogger();

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    @AutoGenerated
    private AbsoluteLayout mainLayout;
    @AutoGenerated
    private NativeButton btnCancel;
    @AutoGenerated
    private NativeButton btnOk;
    @AutoGenerated
    private Label lblPLCConfiguration;
    @AutoGenerated
    private TextField txtRegisterValue;
    @AutoGenerated
    private Label lblRegisterValue;

    private String titleMessage;
    private int registerNumber;

    public ChangeRegisterValueDialog(String titleMessage, int registerNumber) {
        this.titleMessage = titleMessage;
        this.registerNumber = registerNumber;
        buildMainLayout();
        setCompositionRoot(mainLayout);
        initialize();
    }

    private void initialize() {
        try {
            int register = ApplicationServices.getPLCService().readRegister(registerNumber, PLCCommunication.DEFAULT_UNIT_ID);
            BigDecimal registerValue = BigDecimal.valueOf(register).divide(BigDecimal.TEN, 1, BigDecimal.ROUND_HALF_UP);
            txtRegisterValue.setValue(registerValue.toString());

            btnOk.addListener(new Button.ClickListener() {

                private static final long serialVersionUID = -8577869814107324983L;

                @Override
                public void buttonClick(Button.ClickEvent event) {
                    ok();
                }
            });
            btnCancel.addListener(new Button.ClickListener() {

                private static final long serialVersionUID = -4972802977202955811L;

                @Override
                public void buttonClick(Button.ClickEvent event) {
                    cancel();
                }
            });

        } catch (PLCCommunicationException ex) {
            logger.error(ex);
        }
    }

    private void ok() {
        try {
            BigDecimal registerValue = new BigDecimal((String) txtRegisterValue.getValue());
            int register = registerValue.multiply(BigDecimal.TEN).setScale(0, BigDecimal.ROUND_HALF_UP).intValue();
            ApplicationServices.getPLCService().writeRegister(registerNumber, register, InitApplication.UNIT_ID);

            if (getWindow() != null && getWindow().getParent() != null) {
                getWindow().getParent().removeWindow(getWindow());
            }
        } catch (NumberFormatException ex) {
            logger.error(ex.getMessage());
        } catch (PLCCommunicationException ex) {
            logger.error(ex);
        }
    }

    private void cancel() {
        if(getWindow() != null && getWindow().getParent() != null) {
            getWindow().getParent().removeWindow(getWindow());
        }
    }

    @AutoGenerated
    private AbsoluteLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new AbsoluteLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("360px");
        mainLayout.setHeight("180px");

        // top-level component properties
        setWidth("360px");
        setHeight("180px");

        // lblTimeout
        lblRegisterValue = new Label();
        lblRegisterValue.setImmediate(false);
        lblRegisterValue.setWidth("160px");
        lblRegisterValue.setHeight("25px");
        lblRegisterValue.setValue("Nuevo valor del registro:");
        mainLayout.addComponent(lblRegisterValue, "top:60.0px;left:20.0px;");

        // txtPort
        txtRegisterValue = new TextField();
        txtRegisterValue.setImmediate(false);
        txtRegisterValue.setWidth("100.0%");
        txtRegisterValue.setHeight("25px");
        mainLayout.addComponent(txtRegisterValue,
                "top:60.0px;right:20.0px;left:180.0px;");

        // lblPLCConfiguration
        lblPLCConfiguration = new Label();
        lblPLCConfiguration.setImmediate(false);
        lblPLCConfiguration.setWidth("100.0%");
        lblPLCConfiguration.setHeight("20px");
        lblPLCConfiguration
                .setValue("<font size=\"4\"><center><b>" + titleMessage + "</b></center>");
        lblPLCConfiguration.setContentMode(3);
        mainLayout.addComponent(lblPLCConfiguration,
                "top:20.0px;right:20.0px;left:20.0px;");

        // btnOk
        btnOk = new NativeButton();
        btnOk.setCaption("Aceptar");
        btnOk.setImmediate(true);
        btnOk.setWidth("120px");
        btnOk.setHeight("38px");
        mainLayout.addComponent(btnOk, "top:122.0px;left:40.0px;");

        // btnCancel
        btnCancel = new NativeButton();
        btnCancel.setCaption("Cancelar");
        btnCancel.setImmediate(true);
        btnCancel.setWidth("120px");
        btnCancel.setHeight("38px");
        mainLayout.addComponent(btnCancel, "top:122.0px;left:200.0px;");

        return mainLayout;
    }
}
