package co.edu.udistrital.view.control;

import co.edu.udistrital.view.InitApplication;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.NativeButton;

public class ControlWindow extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;

	@AutoGenerated
	private NativeButton btnTemperatureTurnOff;

	@AutoGenerated
	private NativeButton btnPressureTurnOff;

	@AutoGenerated
	private NativeButton btnTemperatureTurnOn;

	@AutoGenerated
	private NativeButton btnPressureTurnOn;

	@AutoGenerated
	private NativeButton btnMemoryMap;

	@AutoGenerated
	private NativeButton btnLastRecords;

	@AutoGenerated
	private NativeButton btnCurrentStatus;

	@AutoGenerated
	private NativeButton btnConfiguration;

	private static final long serialVersionUID = -4124516563611187464L;

	private final InitApplication initApplication;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public ControlWindow(InitApplication initApplication) {
		this.initApplication = initApplication;
		buildMainLayout();
		setCompositionRoot(mainLayout);
		initialize();
	}
	
	private void initialize() {
		btnConfiguration.addListener(new Button.ClickListener() {

            private static final long serialVersionUID = 1763762022344089588L;

			@Override
			public void buttonClick(ClickEvent event) {
				initApplication.showConfigurationWindow();
			}
		});
		btnCurrentStatus.addListener(new Button.ClickListener() {

            private static final long serialVersionUID = -688571120433290392L;

			@Override
			public void buttonClick(ClickEvent event) {
				initApplication.showCurrentStatusWindow();
			}
		});
		btnLastRecords.addListener(new Button.ClickListener() {

            private static final long serialVersionUID = 5694900205721293001L;

			@Override
			public void buttonClick(ClickEvent event) {
				initApplication.showLastRecordsWindow();
			}
		});
		btnMemoryMap.addListener(new Button.ClickListener() {

            private static final long serialVersionUID = 1362297965791130357L;

			@Override
			public void buttonClick(ClickEvent event) {
				initApplication.showMemoryMapWindow();
			}
		});
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("580px");
		mainLayout.setHeight("400px");
		
		// top-level component properties
		setWidth("580px");
		setHeight("400px");
		
		// btnConfiguration
		btnConfiguration = new NativeButton();
		btnConfiguration.setCaption("Configuración");
		btnConfiguration.setIcon(new ThemeResource(
				"img/settings-icon-72x72.png"));
		btnConfiguration.setImmediate(true);
		btnConfiguration.setWidth("86px");
		btnConfiguration.setHeight("86px");
		mainLayout.addComponent(btnConfiguration, "top:300.0px;left:136.0px;");
		
		// btnCurrentStatus
		btnCurrentStatus = new NativeButton();
		btnCurrentStatus.setCaption("Estado actual");
		btnCurrentStatus.setIcon(new ThemeResource(
				"img/current-status-icon-72x72.png"));
		btnCurrentStatus.setImmediate(true);
		btnCurrentStatus.setWidth("86px");
		btnCurrentStatus.setHeight("86px");
		mainLayout.addComponent(btnCurrentStatus, "top:300.0px;left:247.0px;");
		
		// btnLastRecords
		btnLastRecords = new NativeButton();
		btnLastRecords.setCaption("Últimos Registros");
		btnLastRecords.setIcon(new ThemeResource(
				"img/last-records-icon-72x72.png"));
		btnLastRecords.setImmediate(true);
		btnLastRecords.setWidth("86px");
		btnLastRecords.setHeight("86px");
		mainLayout.addComponent(btnLastRecords, "top:300.0px;left:358.0px;");
		
		// btnMemoryMap
		btnMemoryMap = new NativeButton();
		btnMemoryMap.setCaption("Mapa de memoria");
		btnMemoryMap
				.setIcon(new ThemeResource("img/memory-map-icon-72x72.png"));
		btnMemoryMap.setImmediate(true);
		btnMemoryMap.setWidth("86px");
		btnMemoryMap.setHeight("86px");
		mainLayout.addComponent(btnMemoryMap, "top:300.0px;left:469.0px;");
		
		// btnPressureTurnOn
		btnPressureTurnOn = new NativeButton();
		btnPressureTurnOn.setCaption("NativeButton");
		btnPressureTurnOn.setIcon(new ThemeResource(
				"img/turn-on-icon-72x72.png"));
		btnPressureTurnOn.setImmediate(true);
		btnPressureTurnOn.setWidth("86px");
		btnPressureTurnOn.setHeight("86px");
		mainLayout.addComponent(btnPressureTurnOn, "top:40.0px;left:173.0px;");
		
		// btnTemperatureTurnOn
		btnTemperatureTurnOn = new NativeButton();
		btnTemperatureTurnOn.setCaption("NativeButton");
		btnTemperatureTurnOn.setIcon(new ThemeResource(
				"img/turn-on-icon-72x72.png"));
		btnTemperatureTurnOn.setImmediate(true);
		btnTemperatureTurnOn.setWidth("86px");
		btnTemperatureTurnOn.setHeight("86px");
		mainLayout.addComponent(btnTemperatureTurnOn,
				"top:40.0px;left:320.0px;");
		
		// btnPressureTurnOff
		btnPressureTurnOff = new NativeButton();
		btnPressureTurnOff.setCaption("NativeButton");
		btnPressureTurnOff.setIcon(new ThemeResource(
				"img/turn-off-icon-72x72.png"));
		btnPressureTurnOff.setImmediate(true);
		btnPressureTurnOff.setWidth("86px");
		btnPressureTurnOff.setHeight("86px");
		mainLayout
				.addComponent(btnPressureTurnOff, "top:140.0px;left:173.0px;");
		
		// btnTemperatureTurnOff
		btnTemperatureTurnOff = new NativeButton();
		btnTemperatureTurnOff.setCaption("NativeButton");
		btnTemperatureTurnOff.setIcon(new ThemeResource(
				"img/turn-off-icon-72x72.png"));
		btnTemperatureTurnOff.setImmediate(true);
		btnTemperatureTurnOff.setWidth("86px");
		btnTemperatureTurnOff.setHeight("86px");
		mainLayout.addComponent(btnTemperatureTurnOff,
				"top:140.0px;left:320.0px;");
		
		return mainLayout;
	}

}
