package co.edu.udistrital.view.configuration;

import co.edu.udistrital.view.InitApplication;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.NativeButton;
import com.vaadin.ui.Window;

public class ConfigurationWindow extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;

	@AutoGenerated
	private NativeButton btnMemoryMap;

	@AutoGenerated
	private NativeButton btnLastRecords;

	@AutoGenerated
	private NativeButton btnCurrentStatus;

	@AutoGenerated
	private NativeButton btnControl;

	@AutoGenerated
	private NativeButton btnUserConfiguration;

	@AutoGenerated
	private NativeButton btnNotificationConfiguration;

	@AutoGenerated
	private NativeButton btnEmailConfiguration;

	@AutoGenerated
	private NativeButton btnPLCConfiguration;

	private static final long serialVersionUID = -4124516563611187464L;

	private final InitApplication initApplication;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public ConfigurationWindow(InitApplication initApplication) {
		this.initApplication = initApplication;
		buildMainLayout();
		setCompositionRoot(mainLayout);
		initialize();
	}
	
	private void initialize() {
		btnControl.addListener(new Button.ClickListener() {

			private static final long serialVersionUID = -4021426038318305486L;

			@Override
			public void buttonClick(ClickEvent event) {
				initApplication.showControlWindow();
			}
		});
		btnCurrentStatus.addListener(new Button.ClickListener() {

            private static final long serialVersionUID = -688571120433290392L;

			@Override
			public void buttonClick(ClickEvent event) {
				initApplication.showCurrentStatusWindow();
			}
		});
		btnLastRecords.addListener(new Button.ClickListener() {

            private static final long serialVersionUID = 5694900205721293001L;

			@Override
			public void buttonClick(ClickEvent event) {
				initApplication.showLastRecordsWindow();
			}
		});
		btnMemoryMap.addListener(new Button.ClickListener() {

            private static final long serialVersionUID = 1362297965791130357L;

			@Override
			public void buttonClick(ClickEvent event) {
				initApplication.showMemoryMapWindow();
			}
		});	
		
		btnPLCConfiguration.addListener(new Button.ClickListener() {

            private static final long serialVersionUID = -4021426038318305486L;

			@Override
			public void buttonClick(ClickEvent event) {
				Window container = new Window();
				container.setModal(true);
				container.setResizable(false);
				PLCConfigurationDialog plcConfigurationDialog = new PLCConfigurationDialog();
				container.setContent(plcConfigurationDialog);				
				getWindow().addWindow(container);
			}
		});
		btnEmailConfiguration.addListener(new Button.ClickListener() {

            private static final long serialVersionUID = -5551433266079597447L;

			@Override
			public void buttonClick(ClickEvent event) {
				Window container = new Window();
				container.setModal(true);
				container.setResizable(false);
				EmailConfigurationDialog emailConfigurationDialog = new EmailConfigurationDialog();
				container.setContent(emailConfigurationDialog);
				getWindow().addWindow(container);
			}
		});
		btnNotificationConfiguration.addListener(new Button.ClickListener() {

            private static final long serialVersionUID = -6352767471998739430L;

			@Override
			public void buttonClick(ClickEvent event) {
				Window container = new Window();
				container.setModal(true);
				container.setResizable(false);
				NotificationConfigurationDialog notificationConfigurationDialog = new NotificationConfigurationDialog();
				container.setContent(notificationConfigurationDialog);
				getWindow().addWindow(container);
			}
		});
		btnUserConfiguration.addListener(new Button.ClickListener() {

            private static final long serialVersionUID = -7873102619723719516L;

			@Override
			public void buttonClick(ClickEvent event) {
				Window container = new Window();
				container.setModal(true);
				container.setResizable(false);
				UserConfigurationDialog userConfigurationDialog = new UserConfigurationDialog();
				container.setContent(userConfigurationDialog);
				getWindow().addWindow(container);
			}
		});
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("580px");
		mainLayout.setHeight("400px");
		
		// top-level component properties
		setWidth("580px");
		setHeight("400px");
		
		// btnPLCConfiguration
		btnPLCConfiguration = new NativeButton();
		btnPLCConfiguration.setCaption("Configuración del PLC");
		btnPLCConfiguration.setIcon(new ThemeResource("img/plc-settings-Icon-72x72.png"));
		btnPLCConfiguration.setImmediate(true);
		btnPLCConfiguration.setWidth("86px");
		btnPLCConfiguration.setHeight("86px");
		mainLayout.addComponent(btnPLCConfiguration, "top:97.0px;left:40.0px;");
		
		// btnEmailConfiguration
		btnEmailConfiguration = new NativeButton();
		btnEmailConfiguration.setCaption("Configuración de Correo");
		btnEmailConfiguration.setIcon(new ThemeResource("img/mail-settings-icon-72x72.png"));
		btnEmailConfiguration.setImmediate(true);
		btnEmailConfiguration.setWidth("86px");
		btnEmailConfiguration.setHeight("86px");
		mainLayout.addComponent(btnEmailConfiguration, "top:97.0px;right:320.0px;");
		
		// btnNotificationConfiguration
		btnNotificationConfiguration = new NativeButton();
		btnNotificationConfiguration.setCaption("Configuración de Notificaciones");
		btnNotificationConfiguration.setIcon(new ThemeResource("img/alert-settings-icon-72x72.png"));
		btnNotificationConfiguration.setImmediate(true);
		btnNotificationConfiguration.setWidth("86px");
		btnNotificationConfiguration.setHeight("86px");
		mainLayout.addComponent(btnNotificationConfiguration, "top:97.0px;left:320.0px;");
		
		// btnUserConfiguration
		btnUserConfiguration = new NativeButton();
		btnUserConfiguration.setCaption("Configuración del PLC");
		btnUserConfiguration.setIcon(new ThemeResource("img/user-administration-icon-72x72.png"));
		btnUserConfiguration.setImmediate(true);
		btnUserConfiguration.setWidth("86px");
		btnUserConfiguration.setHeight("86px");
		//mainLayout.addComponent(btnUserConfiguration, "top:97.0px;right:40.0px;");
		
		// btnControl
		btnControl = new NativeButton();
		btnControl.setCaption("Control PLC");
		btnControl.setIcon(new ThemeResource("img/plc-settings-Icon-72x72.png"));
		btnControl.setImmediate(true);
		btnControl.setWidth("86px");
		btnControl.setHeight("86px");
		mainLayout.addComponent(btnControl, "top:300.0px;left:25.0px;");
		
		// btnCurrentStatus
		btnCurrentStatus = new NativeButton();
		btnCurrentStatus.setCaption("Estado actual");
		btnCurrentStatus.setIcon(new ThemeResource("img/current-status-icon-72x72.png"));
		btnCurrentStatus.setImmediate(true);
		btnCurrentStatus.setWidth("86px");
		btnCurrentStatus.setHeight("86px");
		mainLayout.addComponent(btnCurrentStatus, "top:300.0px;left:247.0px;");
		
		// btnLastRecords
		btnLastRecords = new NativeButton();
		btnLastRecords.setCaption("Últimos Registros");
		btnLastRecords.setIcon(new ThemeResource("img/last-records-icon-72x72.png"));
		btnLastRecords.setImmediate(true);
		btnLastRecords.setWidth("86px");
		btnLastRecords.setHeight("86px");
		mainLayout.addComponent(btnLastRecords, "top:300.0px;left:358.0px;");
		
		// btnMemoryMap
		btnMemoryMap = new NativeButton();
		btnMemoryMap.setCaption("Mapa de memoria");
		btnMemoryMap.setIcon(new ThemeResource("img/memory-map-icon-72x72.png"));
		btnMemoryMap.setImmediate(true);
		btnMemoryMap.setWidth("86px");
		btnMemoryMap.setHeight("86px");
		mainLayout.addComponent(btnMemoryMap, "top:300.0px;left:469.0px;");
		
		return mainLayout;
	}

}
